spring.application.name=dhananjay

spring.datasource.url=jdbc:postgresql://localhost:5432/management
spring.datasource.username=postgres
spring.datasource.password=8979985527
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate config
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# JWT config
jwt.secret=9aF$kL8#pQ2!xY7vT@rZ5mN3bH6dS1Wc
jwt.expiration-ms=604800000